### PR TITLE
Closes #20: Allows for processing of models with recursive references…

### LINKED ISSUE #20: Inheritance and Recursion
We ran into a few issues with the bundler relating to inheritance (oneOf, allOf) and recursion. I corrected the issues and wanted to know if you'd accept a PR? The PR fixes these processing issues and also decomposes the processor into 2 classes to better support external integrations e.g. Gradle plugins

### PR DESCRIPTION
**Pull request by jdwoody**
…, inheritance, and better path reference handling.

### CODE REVIEW

**Comment by stevehu** [comment]
@jdwoody Thanks a lot for the contribution. The change is massive and a simple directory comparison is not enough. Dan and I are reviewing the changes line by line. It will take a while, so please be patient.

**Comment by jdwoody** [comment]
@stevehu No worries. Feel free to put any comments in line and I'll be happy to talk through it. I can also add some additional unit tests if that would help.

**Comment by stevehu** [comment]
It would be great if you could add some additional tests. I am working on an external test with an OpenAPI specification with some external references. If the test passes, I would have the confidence to merge it.

**Comment by stevehu** [comment]
@jdwoody The two test cases you have provided are really good to cover different scenarios. There is no need to add another test case. @ddobrin I have reviewed the changes and it looks good to me. Could you please take a look and merge it to master if you are OK with it? Thanks.

**Review by stevehu — APPROVED** [review]

**Pull request merged**
